steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/clv-churn-prediction/clv-churn-app ', '.']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'run', 'deploy', 'clv-churn-service', 
         '--image', 'gcr.io/clv-churn-prediction/clv-churn-app ',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated']